version: '3.8'
services:
  dev:
    container_name: server-dev
    image: server-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: node dist/main
    ports:
      - 3010:3000
      - 9229:9229
    networks:
      - server-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - mongodb
    # environment:
    #   DATABASE_URL: mongodb://mongodb:27017/nest_db

  mongodb:
    image: mongo:latest
    container_name: mongodb
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=pass12345
    networks:
      - server-network
    ports:
      - 27047:27017
    volumes:
      - dbdata:/data/db
    restart: unless-stopped

volumes:
  dbdata:

networks:
  server-network:
    driver: bridge
